// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3L6l9S5YSSzqjplZqaWRv3mFykKKVAd8',
    appId: '1:495106422823:web:cc60dae7239a1282e17602',
    messagingSenderId: '495106422823',
    projectId: 'task-d865d',
    authDomain: 'task-d865d.firebaseapp.com',
    storageBucket: 'task-d865d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC2sjeBoyFLS4TOIOUCdhuEt2ugriM9I4',
    appId: '1:495106422823:android:d8a55ae27d5b5a13e17602',
    messagingSenderId: '495106422823',
    projectId: 'task-d865d',
    storageBucket: 'task-d865d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfvlycZUThQ_eoINd23bPDVd3UkLIVWsE',
    appId: '1:495106422823:ios:3e992bc3dd70633de17602',
    messagingSenderId: '495106422823',
    projectId: 'task-d865d',
    storageBucket: 'task-d865d.firebasestorage.app',
    iosBundleId: 'com.example.coinquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfvlycZUThQ_eoINd23bPDVd3UkLIVWsE',
    appId: '1:495106422823:ios:3e992bc3dd70633de17602',
    messagingSenderId: '495106422823',
    projectId: 'task-d865d',
    storageBucket: 'task-d865d.firebasestorage.app',
    iosBundleId: 'com.example.coinquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3L6l9S5YSSzqjplZqaWRv3mFykKKVAd8',
    appId: '1:495106422823:web:0cd9e0b0943352eee17602',
    messagingSenderId: '495106422823',
    projectId: 'task-d865d',
    authDomain: 'task-d865d.firebaseapp.com',
    storageBucket: 'task-d865d.firebasestorage.app',
  );
}
