platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try re-running flutter precache."
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__)

target 'Runner' do
    use_frameworks!
    pod 'PhoneNumberKit/PhoneNumberKitCore', '3.6.6'
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_post_install target
  end
end
